spring.application.name=hospital-app
server.port=8085

# Ancienne config H2 (référence)
# spring.datasource.url=jdbc:h2:mem:products-db
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3307/products-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
